### ISSUE TITLE
LoginFrame - Coty and Kenadi

### ISSUE THREAD

**Issue by cerisewuthrich** [LegendaryZReborn/4123-DatabaseManagement#27]
I haven't pulled your code, but I looked at it and have a couple of comments.
1.  I want the user to be able to connect to either money database (on cs2 or griffincomplaints).  You can default the database name to money and default the server name to griffincomplaints, but those fields should be editable.

2.  I think the connection should be established (if possible) and then the connection object should be passed to the other frames, don't you, @cotyhamilton?

**Comment by cotyhamilton** [comment]
1. Alright, we'll do that

2. Yeah, I thought that's how it should work, but when I looked at the other frames I couldn't figure out how it was handled. Is how I opened the next frame after login even correct?
