### ISSUE TITLE
Fund Frame Version 2 for 11/13

### ISSUE THREAD

**Issue by cerisewuthrich** [LegendaryZReborn/4123-DatabaseManagement#40]
Remove Contributions, Donors, Funds, Reports buttons.
Implement Table Model
Make both text fields longer
If you switch to another tab, clear out the current contents of text fields

**Comment by t3ll0n** [comment]
RE: "If you switch to another tab, clear out the current contents of text fields"

Can't seem to find an appropriate event on the FundFame that detects when the tabs have been switched (focus, activated, etc. does not work). This may need to be implemented form the MainFrame?

**Comment by cerisewuthrich** [comment]
You may need to add a listener to the tabbed pane in MainFrame.  I am closing this issue since the other items are working, but keep looking into this.
